import Link from "next/link";
import { buildLog, byDay } from "@/lib/build-log";
import { pageMetadata } from "@/lib/seo";
import { Section } from "@/components/Section";

export const metadata = pageMetadata({
  title: "Build log",
  description:
    "What has shipped to the warOnSaaS main branch, generated from the git history and the wave reports. Dates, commits and links only.",
  path: "/log",
});

export default function LogPage() {
  const days = byDay();
  return (
    <>
      <div className="title">
        <p className="label">BUILD LOG // GENERATED FROM GIT</p>
        <h1>Build log</h1>
        <p className="lead">
          Every change that landed on main, newest first, and every wave report. Generated at build time from the
          repository. Nothing on this page is written by hand.
        </p>
      </div>

      <Section n="01" title="WAVE REPORTS" id="reports">
        {buildLog.reports.length ? (
          <dl className="kv">
            {buildLog.reports.map((r) => (
              <div key={r.file}>
                <dt>{r.date ?? "No date line"}</dt>
                <dd>
                  <a href={r.url}>{r.title}</a>
                  <span className="fine">
                    {" "}
                    Gate results: {r.results.pass} PASS, {r.results.partial} PASS (partial), {r.results.pending} PENDING,{" "}
                    {r.results.fail} FAIL.
                  </span>
                </dd>
              </div>
            ))}
          </dl>
        ) : (
          <p>No wave reports yet.</p>
        )}
      </Section>

      <Section n="02" title="COMMITS ON MAIN" id="commits" aside={`${buildLog.count} ENTRIES`}>
        <p className="fine">
          First-parent history of main: a merged branch appears as one entry. Commit subjects are quoted exactly as
          written.{buildLog.complete ? "" : " This build had a shallow copy of the history, so older entries are missing."}
        </p>
        {days.map((d) => (
          <div key={d.day}>
            <h3>{d.day}</h3>
            <ol className="rules">
              {d.commits.map((c) => (
                <li key={c.sha}>
                  <span>
                    <a href={c.url}>{c.short}</a>
                  </span>
                  <span>
                    <code data-verbatim="">{c.subject}</code> <span className="dim">{c.date.slice(11, 16)}</span>
                  </span>
                </li>
              ))}
            </ol>
          </div>
        ))}
      </Section>

      <Section title="SOURCE" id="source">
        <p className="fine">
          Generated by apps/web/scripts/gen-log.mjs from {buildLog.ref} at {buildLog.head ? buildLog.head.slice(0, 7) : "no commit"}.{" "}
          <Link href="/">Back to the Sniper List</Link>.
        </p>
      </Section>
    </>
  );
}
