#!/usr/bin/env node
/**
 * Copies the shared files the site needs from the monorepo into apps/web/generated/,
 * because the Vercel deploy uploads apps/web only (apps/web is not yet a workspace; see
 * blockers/B-0001-web.md). The copies are committed so the Vercel build has them.
 *
 *   docs/roadmap/waronsaas.roadmap.json  -> generated/waronsaas.roadmap.json   (byte-identical)
 *   packages/contracts/src/progress.ts   -> generated/contracts-progress.ts   (identical except its one
 *                                           type-only import, re-pointed at the contracts source)
 *   docs/whitepaper/WHITEPAPER.md        -> generated/WHITEPAPER.md          (byte-identical; the /whitepaper
 *                                           page and /whitepaper.md render it; its date comes from gen-log.mjs)
 *
 * With the repo present (local builds): writes the copies, or with --check fails if they differ.
 * Without the repo (Vercel): checks the committed copies exist and exits 0.
 */
import { existsSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";

const web = process.cwd();
const repo = join(web, "..", "..");
const check = process.argv.includes("--check");

const IMPORT_FROM = 'from "./primitives.js";';
const IMPORT_TO = 'from "@contracts/primitives";';

const files = [
  { from: join(repo, "docs/roadmap/waronsaas.roadmap.json"), to: join(web, "generated/waronsaas.roadmap.json"), map: (s) => s },
  { from: join(repo, "docs/whitepaper/WHITEPAPER.md"), to: join(web, "generated/WHITEPAPER.md"), map: (s) => s },
  {
    from: join(repo, "packages/contracts/src/progress.ts"),
    to: join(web, "generated/contracts-progress.ts"),
    map: (s) => {
      if (s.split(IMPORT_FROM).length !== 2) throw new Error("progress.ts: expected exactly one import from ./primitives.js");
      return `// GENERATED by scripts/sync-shared.mjs from packages/contracts/src/progress.ts. Do not edit.\n${s.replace(IMPORT_FROM, IMPORT_TO)}`;
    },
  },
];

mkdirSync(join(web, "generated"), { recursive: true });
let failed = false;
for (const f of files) {
  if (!existsSync(f.from)) {
    if (!existsSync(f.to)) {
      console.error(`sync-shared: missing ${f.to} and no source ${f.from}`);
      failed = true;
    }
    continue;
  }
  const want = f.map(readFileSync(f.from, "utf8"));
  const have = existsSync(f.to) ? readFileSync(f.to, "utf8") : null;
  if (have === want) continue;
  if (check) {
    console.error(`sync-shared: ${f.to} is stale; run node scripts/sync-shared.mjs`);
    failed = true;
  } else {
    writeFileSync(f.to, want);
    console.log(`sync-shared: wrote ${f.to}`);
  }
}
if (failed) process.exit(1);
console.log("sync-shared: OK");
