// Bundles the target scans (docs/scans/<target>.md, warOnSaaS/wos) into the control plane as
// src/generated/scans.ts, so roadmap authors and reviewers (network: false) get their target's scan as a
// server document `wos:scan/<target>`, pinned by content: the file's git blob oid and sha256 are recorded here and the
// rendered document's sha256 goes into the plan and the context manifest (first-run fix B4).
// Usage: node services/control-plane/scripts/gen-scans.mjs [--check]   (--check fails when the generated file is stale)
import { createHash } from "node:crypto";
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("../../../", import.meta.url));
const out = fileURLToPath(new URL("../src/generated/scans.ts", import.meta.url));
// The target scans: one lowercase slug per file; README, OVERLAP and VOCABULARY are not target scans.
const files = readdirSync(`${root}docs/scans`)
  .filter((f) => /^[a-z][a-z0-9-]*\.md$/.test(f))
  .sort();

export function render() {
  const entries = files.map((f) => {
    const bytes = readFileSync(`${root}docs/scans/${f}`);
    const blob = createHash("sha1").update(`blob ${bytes.length}\0`).update(bytes).digest("hex");
    const sha256 = `sha256:${createHash("sha256").update(bytes).digest("hex")}`;
    const slug = f.slice(0, -3);
    const key = /^[a-z][a-z0-9]*$/.test(slug) ? slug : JSON.stringify(slug);
    return `  ${key}: {\n    path: ${JSON.stringify(`docs/scans/${f}`)},\n    gitBlobOid: ${JSON.stringify(blob)},\n    sha256: ${JSON.stringify(sha256)},\n    text: ${JSON.stringify(bytes.toString("utf8"))},\n  },`;
  });
  return `// GENERATED by services/control-plane/scripts/gen-scans.mjs from docs/scans/*.md. Do not edit; rerun the script.
// test/scans.test.ts fails when this file is stale.
export interface BundledScan {
  path: string;
  gitBlobOid: string;
  sha256: string;
  text: string;
}

export const BUNDLED_SCANS: Readonly<Record<string, BundledScan>> = {
${entries.join("\n")}
};
`;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const text = render();
  if (process.argv.includes("--check")) {
    let current = "";
    try {
      current = readFileSync(out, "utf8");
    } catch {}
    if (current !== text) {
      console.error("services/control-plane/src/generated/scans.ts is stale: run node services/control-plane/scripts/gen-scans.mjs");
      process.exit(1);
    }
    console.log("bundled scans are current");
  } else {
    writeFileSync(out, text);
    console.log(`wrote ${files.length} scans to ${out}`);
  }
}
